### ISSUE TITLE
App window does not quit on close

### ISSUE THREAD

**Issue by mirukuz** [awohletz/electron-prisma-trpc-example#1]
Thanks for building the app, love how neat and slick it is! I've used it for my own app and found a small bug:

**Operating system**:  mac OS 12
**Version of the template**: LTS

## How to reproduce
- `npm run start` the app
- Close the app using the red button on the top left
- click on the icon on the dock
- can see an empty page 
- In the terminal, can see this error message: 

```
(node:11907) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

## Expected behavior
I guess the expected behavior is when we close by X and click on the doc to open it again, it should display the same screen when we left?

**Comment by awohletz** [comment]
Thanks for reporting. It was throwing an error trying to register the ipcMain handler again on re-opening the window. I've moved the handler registration to `whenReady` as shown here: https://www.electronjs.org/docs/latest/tutorial/ipc#1-listen-for-events-with-ipcmainhandle
